# Generated by Django 5.2.4 on 2025-07-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_flor_imagen_alter_pedidoitem_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(default='Sin dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='correo@ejemplo.com', max_length=20),
            preserve_default=False,
        ),
    ]
