# Generated by Django 5.2.4 on 2025-07-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_creado_pedido_creado_en_remove_pedido_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
